spring:
  data:
    mongodb:
      port: 27017
      database: proddb
#  shell:
#    interactive:
#      enabled: false


  datasource:
    url: jdbc:postgresql://localhost:5432/denisdb
    username: postgres
    password: postgres

    #initialization-mode: never # put 'always' for creating tables at initial state

  batch:
    initialize-schema: always
    job:
      enabled: false

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect