spring:
  data:
    mongodb:
      port: 27017
      database: proddb
  shell:
    interactive:
      enabled: true


  datasource:
    url: jdbc:postgresql://localhost:5432/destdb
    username: postgres
    password: postgres
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect


  batch:
    initialize-schema: always
    job:
      enabled: false